### ISSUE TITLE
Facet bug

### ISSUE THREAD

**Issue by ivan-kleshnin** [Yomguithereal/baobab#305]
```js
import Baobab from "baobab";

let state = new Baobab(
  {
    ajaxQueue: [],

    foo: {
      $bar: [
        ["xxx"],
        function () {
          return true;
        }
      ],
    },
  },
  { // OPTIONS
    immutable: false
  }
);

state.select("foo").get();

state.select("ajaxQueue").push({});
```

```
Error: Baobab.Facet: attempting to create a computed data node with a wrong definition (path: /foo/$bar).
    at makeError (/.../node_modules/baobab/dist/helpers.js:429:13)
    at new Facet (/.../node_modules/baobab/dist/facet.js:46:36)
    at walk (/.../node_modules/baobab/dist/baobab.js:182:27)
    at walk (/.../node_modules/baobab/dist/baobab.js:186:15)
    at Baobab._refreshComputedDataIndex (/.../node_modules/baobab/dist/baobab.js:202:16)
    at Baobab.update (/.../node_modules/baobab/dist/baobab.js:306:12)
    at Cursor.(anonymous function) [as push] (/.../node_modules/baobab/dist/cursor.js:800:22)
    at Object.<anonymous> (/.../test.js:23:27)
    at Module._compile (module.js:460:26)
    at normalLoader (/usr/local/lib/node_modules/babel/node_modules/babel-core/lib/babel/api/register/node.js:147:5)
```

To replicate the error next 4 things are required:

1) Declare nested facet
2) Set immutable = false
3) Read from nested facet
4) Write somewhere in the tree

:laughing: 

Verified in Node and Chrome.

**Comment by Yomguithereal** [comment]
Ok. Will test this asap and see where I went wrong.

**Comment by Yomguithereal** [comment]
Latest commit should solve your issue but is only part of the solution. I've discovered complexities that I should solve properly here.

**Comment by Yomguithereal** [comment]
Underlying problem should be completely fixed now. Will publish a `dev` version soon.

**Comment by ivan-kleshnin** [comment]
Checked in `dev11`, problem persists: the code from first post still fails.

**Comment by Yomguithereal** [comment]
You are right indeed. The issue even occurs with immutability on now :). Let me fix that once and for all.

**Comment by Yomguithereal** [comment]
Should be solved by `2.0.0-dev12` (hopefully).

**Comment by ivan-kleshnin** [comment]
Fixed.
